version: 1.2.{build}
skip_tags: true
os: Visual Studio 2017
configuration: Release
platform: AnyCPU
test: off
branches:
  only:
  - master
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  NuGetApiKey:
    secure: 0+4uMr/wsyh8BisfHCwkDbaWwzmKNvvB2MwFz45/ePwbOMB6WT1AfhzujeddcN/2
  CoverallsRepoToken:
    secure: dVnmCYP9Jc9I11IFY/4JaIaNLQqKEVCV92P0cJsxRlw6CZfhPTL/JcJhtIAkHhVu
build_script:
- ps: .\build.ps1 --settings_skipverification=true
cache:
  - tools -> tools/packages.config
artifacts:
- path: artifacts\**\*.nupkg
- path: artifacts\**\site.zip
notifications:
- provider: Email
  to:
  - robin@dapplo.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
