version: 1.0.{build}
skip_tags: true
configuration: Release
platform: AnyCPU
clone_depth: 2
test: off
branches:
  only:
  - master
install:
- choco install gitlink -y
- choco install docfx -y
before_build:
- ps: .\SetVersion.ps1
- appveyor-retry dotnet restore -v Minimal
- ps: if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { $env:is_not_pr = "true"; }
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  NuGetApiKey:
    secure: xkDQ385+smLqdzhESsXBJvnUjK4FZ4Djjrqi9tFR29dwESIvPYOrQAqgri5Nf/fA
  COVERALLS_REPO_TOKEN:
    secure: dVnmCYP9Jc9I11IFY/4JaIaNLQqKEVCV92P0cJsxRlw6CZfhPTL/JcJhtIAkHhVu
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
build_script:
- dotnet build src/Dapplo.Log -c %CONFIGURATION% --no-dependencies
- dotnet build src/Dapplo.Log.LogFile -c %CONFIGURATION% --no-dependencies
- dotnet build src/Dapplo.Log.Loggers -c %CONFIGURATION% --no-dependencies
- dotnet build src/Dapplo.Log.XUnit -c %CONFIGURATION% --no-dependencies
- dotnet build src/Dapplo.Log.Tests -c %CONFIGURATION% --no-dependencies
- dotnet build src/Dapplo.Log.ConsoleExample -c %CONFIGURATION% --no-dependencies
after_build:
- GitLink .\
- docfx doc\docfx.json
- 7z a -tzip %APPVEYOR_BUILD_FOLDER%\artifacts\site.zip -r %APPVEYOR_BUILD_FOLDER%\doc\_site\*.*
- dotnet pack src/Dapplo.Log -c %CONFIGURATION% --no-build -o artifacts
- dotnet pack src/Dapplo.Log.LogFile -c %CONFIGURATION% --no-build -o artifacts
- dotnet pack src/Dapplo.Log.Loggers -c %CONFIGURATION% --no-build -o artifacts
- dotnet pack src/Dapplo.Log.XUnit -c %CONFIGURATION% --no-build -o artifacts
# This runs the tests with OpenCover and publishes the report to Coverall
- ps: .\CreateCoverage.ps1
#cache:
#- '%USERPROFILE%\.nuget\packages'
artifacts:
- path: artifacts\**\*.nupkg
- path: artifacts\**\site.zip
notifications:
- provider: Email
  to:
  - robin@dapplo.net
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
deploy:
- provider: NuGet
  skip_symbols: true
  api_key:
    secure: xkDQ385+smLqdzhESsXBJvnUjK4FZ4Djjrqi9tFR29dwESIvPYOrQAqgri5Nf/fA
  on:
    branch: master
    is_not_pr: true
    appveyor_repo_commit_message_extended: /\[release\]/
